// Code generated by protoc-gen-go. DO NOT EDIT.
// source: example.proto

package example

// This file should be skipped by the scanner.
// Generated files add noise to the index.

type GeneratedMessage struct {
	Field1 string
	Field2 int
}

func NewGeneratedMessage() *GeneratedMessage {
	return &GeneratedMessage{}
}
